### ISSUE TITLE
use unicode compadible font

### ISSUE THREAD

**Issue by zaze06** [fauxpark/oled-core#2]
Hi i'm whunder if i can esly convert a ttc font to a font that i can use whit this library.

**Comment by fauxpark** [comment]
No, this library only works with fixed-width fonts in the form outlined by [the Font interface](https://github.com/fauxpark/oled-core/blob/main/src/main/java/net/fauxpark/oled/font/Font.java). Although the type of `getGlyphs()` is `int` I have not tested it with a font height larger than 8 pixels and the text drawing code likely will not work.

**Comment by zaze06** [comment]
Ok thanks, than if i may ask do you know of a library that might support this? or shall I search the web for one?

**Comment by fauxpark** [comment]
I don't, sorry.

**Comment by zaze06** [comment]
Ok, thanks for the help anyways.
